name: Test and Publish TestPyPI

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

permissions:
  contents: write

jobs:

  test:
    name: Test 🧪
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle src/sankey_cashflow
    - name: Run tests
      run: |
        pip install coverage pytest
        coverage run -m pytest
        coverage report
        coverage xml
        coverage html
    - name: Generate badges
      run: |
        pip install genbadge defusedxml
        genbadge coverage -i coverage.xml -o htmlcov/coverage-badge.svg
    - name: Remove gitignore from coverage
      run: rm -f htmlcov/.gitignore
    - name: Write coverage to gh-pages
      if: success() || failure()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: htmlcov
        single-commit: true

  build:
    name: Build distribution 🔨
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-test-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish 📦 to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/sankey-cash

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-test-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/  